server:
  port: 9006
eureka:
  client:
    service-url:
      defaulZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: dym-itempage
  main:
    allow-bean-definition-overriding: true
#超时配置
ribbon:
  ReadTimeout: 9000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# 生成静态页的位置
pagepath: D:\develop\data\dongyimai-parent\items