server:
  port: 9006
spring:
  application:
    name: dym-sms
  rabbitmq:
    host: 192.168.1.200
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
sms:
  appcode: 1b58a294f24c492d8678599edb88b029  #使用自己的AppCode
  tpl_id: TP1711063    # 默认模板