spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "*" #跨域处理允许所有的域
            allowedMethods: #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: user-route
          uri: lb://dym-user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
        - id: goods-route
          uri: lb://dym-sellergoods
          predicates:
            - Path=/api/brand/**,/api/goods/**
          filters:
            - StripPrefix=1

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka